CMPUT301W17T12/ProjectAttitude

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/EditMoodActivity.java, ProjectAttitude/app/src/main/res/layout/activity_create_mood.xml, ProjectAttitude/app/src/main/res/values/strings.xml
=> Added Edit Mood UI

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Abstracts/DatePickerEditText.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/EditMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Adapters/MoodMainAdapter.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/ColorMap.java, ProjectAttitude/app/src/main/res/layout/activity_edit_mood.xml, ProjectAttitude/app/src/main/res/layout/activity_view_mood.xml, ProjectAttitude/app/src/main/res/values/strings.xml
View mood is done, did some smaller things as well, check commits for details
=> View Mood 99% done

ProjectAttitude/app/build.gradle, ProjectAttitude/app/src/debug/res/values/google_maps_api.xml, ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MapActivity.java, ProjectAttitude/app/src/main/res/layout/activity_main.xml, ProjectAttitude/app/src/main/res/layout/activity_map.xml, ProjectAttitude/app/src/main/res/values/strings.xml, ProjectAttitude/build.gradle
This is currently using OSM for android as suggested by the TA. No functionality yet, I haven't figured that out yet.
=> Map exists

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/MainController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/MoodList.java, ProjectAttitude/app/src/main/res/drawable/search_button.xml, ProjectAttitude/app/src/main/res/layout/activity_main.xml
Read commits for full description
=> Filtermoods merge - more fixes and more bugs

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/app/build.gradle, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/MainController.java, ProjectAttitude/app/src/main/res/menu/main_menu.xml, ProjectAttitude/app/src/test/java/com/projectattitude/projectattitude/MoodListTest.java, ProjectAttitude/app/src/test/java/com/projectattitude/projectattitude/MoodTest.java
Bug is that sort and filter only work once because moodList.clone() isn't quite working yet or adapter isn't being notified?? Still figuring out the bug but...
TO TEST:
Open app.
Sort or filter.
Close app.
Rinse and repeat. Open and close app when adding, deleting, or editing moods to see changes.
=> All Sorts and Filters fully functional... but bug introduced

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/MoodList.java, ProjectAttitude/app/src/test/java/com/projectattitude/projectattitude/MoodTest.java
=> Refresh moods by clicking ALL MOODS

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/LoginActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchUserController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/UserController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/User.java
Accounts sync to db, register/login works. Keeps track of added moods. Doesn't filter since moods are stored differently, shouldn't be a bad fix. Moods that appear in ListView are moods stored in db corresponding to user.
=> Accounts sync

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/MainController.java
=> EditMood should work, filtering should work, displaying shud work

ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/LoginActivity.java
Can now log in from an emulator, might still have connection problems elsewhere
=> Fixed log ins for emulators

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/LoginActivity.java
Fixed how we deal with log ins.
Wasn't terribly clean about removing old code, just put a new function in main and log in and used that instead.
=> Emulators should work just fine now

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java
Reverts CMPUT301W17T12/ProjectAttitude#62
=> Revert "fixed dele/edit/view position filter issue"

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java
Reverts CMPUT301W17T12/ProjectAttitude#67
=> Unrevert everything

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/res/menu/time_menu.xml, ProjectAttitude/app/src/main/res/values/strings.xml
=> Added week Option + fixed edit bug

ProjectAttitude/app/build.gradle, ProjectAttitude/app/src/androidTest/java/com/projectattitude/projectattitude/MainActivityUITest.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/res/layout/activity_create_mood.xml, ProjectAttitude/app/src/main/res/layout/activity_view_profile.xml
Boris' cases still dont work but filter is almost there.
Current problem is it clicks the mood with the text "angry" instead of the filter menu text angry
Commented out test filter by day
=> Intent testing back to working as it was

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java
The profile page seems to be working?
=> Profile page works?

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/CreateMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MapActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/Mood.java
Started some minor work on maps. The map now displays a single pin over Edmonton as a test.
We need to go back and make it so that you can save your location when creating and editing a mood. I didn't get it to work unfortunately.
=> Added a simple marker positioned on Edmonton

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/androidTest/java/com/projectattitude/projectattitude/MainActivityUITest.java
All test cases now work
Added profile test case
=> Test case work

.gitignore, ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/build.gradle, ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewNotificationsActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/res/layout/activity_main.xml, ProjectAttitude/app/src/main/res/layout/activity_view_notifications.xml, ProjectAttitude/app/src/main/res/layout/notification_item.xml, ProjectAttitude/app/src/test/java/com/projectattitude/projectattitude/MoodTest.java
Profile can now view tweets that you click on
Created a notifications page that would handle accepting follow requests and anything else we need between users.
Created a notifications item that contains a text and a button for accept and one for deny. This is to be used in the notifications page.
Could replace the item with a popup toast or something that asks deny or accept.
Might have broken unit tests? Commented out a few tests that made my gradle start breaking. Might have been due to trying to get location to work.
=> Created notifications framework

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/androidTest/java/com/projectattitude/projectattitude/MainActivityUITest.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/MainController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/FilterDecorator.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/FilterDecoratorHandler.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/FilterEmotionDecorator.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/FilterTimeDecorator.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/FilterTriggerDecorator.java, ProjectAttitude/app/src/main/res/drawable/clear_button.xml, ProjectAttitude/app/src/main/res/layout/activity_main.xml, ProjectAttitude/app/src/main/res/menu/filter_menu.xml, ProjectAttitude/app/src/main/res/menu/mood_menu.xml, ProjectAttitude/app/src/main/res/menu/sort_filter_menu.xml, ProjectAttitude/app/src/main/res/menu/time_menu.xml, ProjectAttitude/app/src/main/res/values/strings.xml
Took way too much time, but filtering now uses decorator classes to filter things.
-Checkables can be seen in all menus: including sort and filter!
-Alot of dead code inside of controller now (most filter code moved to decorators)
-Replaced obsolete onClick functions in menu
-Multifiltering works with unchecking filters. A clear button is added for to 'clear' trigger filtering.
-Fixed tests (I think?) to work with new menu changes.
=> Whole redesign of filtering - Multi filtering works in simulator

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/CreateMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/EditMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/GPSTracker.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/Mood.java, ProjectAttitude/app/src/main/res/layout/activity_create_mood.xml, ProjectAttitude/app/src/main/res/values/strings.xml
- Editing/Adding of locations attached to moods is possible.
- TextView to display location is wonky. Someone who knows how to deal with constraints should fix it
- Seeing the location in the view mood activity is missing, i dont know how constraint stuff works
=> Location moods

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MapActivity.java
user moods that have location attached will be placed on map
=> Map markers

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/GPSTracker.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MapActivity.java
filtered moods are now shown on the map
=> moodlists appear on markers

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/EndlessScrollListener.java
Found a class to help create the appropriate scrolling interface for pagination but haven't actually touched the database or the ElasticSearchController stuff.
=> Minor Startup towards Pagination

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MapActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java
-User's can't follow themselves or others repeatedly
-map function for calculating distance added, not used yet
=> User's can't follow themselves or others repeatedly, map function added

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchRequestController.java
-Adding requests and its base cases are tested and finished (No intent tests yet though)
-Accepting and denying requests work
TODOS:
Seeing who you're following doesn't function correctly yet
No intent tests.
=> Notifications and requests are fully functional!!

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchRequestController.java
Reverts CMPUT301W17T12/ProjectAttitude#106, app is broken.
=> Revert "Notifications and requests are fully functional!!"

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/LoginActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/UserController.java
Reverts CMPUT301W17T12/ProjectAttitude#105, reverting this, so app doesn't crash on start.
=> Revert "Login persistence"

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/res/layout/activity_main.xml
-Following User moods are still visible in the profile page.
-Filtering isn't working, probably did something wrong.
=> Merged Following Users Into MainView

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/androidTest/java/com/projectattitude/projectattitude/MainActivityUITest.java, ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchRequestController.java, ProjectAttitude/app/src/main/res/layout/activity_view_profile.xml
Also fixed more intents.
It seems elastic search is down? So I can't add the image to user so it becomes associated with them
=> Image for profiles!

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchRequestController.java
Refer to previous revert if you want a changelog (it's quite short).
- Reverted the revert manually by adding the changes i changed for each file
=> Reverting the revert of making requests work - It works!

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java
Title. You can see your following list now.
=> small change to make following work

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/CreateMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/EditMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchUserController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/MainController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/EndlessScrollListener.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/User.java, ProjectAttitude/app/src/test/java/com/projectattitude/projectattitude/MoodTest.java
Basically title.
Changelog: Filtering followed mood list works.
Bugs found: Nothing yet
TODOs: Intent testing for following filtered moods?
=> Filtering following moods list works. - tested

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/MainController.java, ProjectAttitude/app/src/test/java/com/projectattitude/projectattitude/FilterTest.java
HEAVY NOTE: FilterTest (junit) IS NO LONGER FUNCTIONAL DO NOT USE,
Change log:
- Fixed bug that created user when requesting for a non-existent user
- Refactored controller class's sort function
- Most recent moods in followed lists are now working! May need to reset database to see it 100% working.
=> Alot of bug fixes - request and sorting related

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchUserController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/User.java, ProjectAttitude/app/src/test/java/com/projectattitude/projectattitude/FilterTest.java
Changelog:
- Fixed multiple bugs described in commits
- Profile picture is now saved/viewable on database
=> Bug fixes and online profile picture implementation

ProjectAttitude/.idea/misc.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MapActivity.java
5KM distance stuff should work now
=> new formula for 5km distances

ProjectAttitude/.idea/gradle.xml, ProjectAttitude/app/src/main/AndroidManifest.xml, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewOtherProfileActivity.java, ProjectAttitude/app/src/main/res/layout/activity_view_mood.xml, ProjectAttitude/app/src/main/res/layout/activity_view_other_profile.xml, ProjectAttitude/app/src/main/res/layout/activity_view_profile.xml
Added new activity which includes a new ui layout, with the adding of users removed.
Added a button to view mood to go to the users profile (Not functional yet)
=> Added new activity for viewing others profile, and other ui

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/LoginActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MapActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/UserController.java, ProjectAttitude/app/src/main/res/layout/mood_main_item.xml
opens viewMood when marker info box clicked
Login persistence currently works, intent tests will need to be adjusted to handle that
=> Added onClick for marker info box And implemented login persistence

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/MainActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewMoodActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewOtherProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Adapters/RequestAdapter.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchUserController.java, ProjectAttitude/app/src/main/res/layout/activity_view_mood.xml, ProjectAttitude/app/src/main/res/layout/activity_view_other_profile.xml, ProjectAttitude/app/src/main/res/layout/activity_view_profile.xml
Changelog:
Title
UI works
Viewing other profiles through moods work
bug fixes
=> Following and followedList works in profile

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewNotificationsActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Adapters/RequestAdapter.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Controllers/ElasticSearchRequestController.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/FollowRequest.java, ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Objects/User.java
=> new implementation of notifications - UNTESTED CAPITALS

ProjectAttitude/app/src/main/java/com/projectattitude/projectattitude/Activities/ViewProfileActivity.java
=> IMPLEMENTATION OF REQUESTS WORKS WITH CAPITALS
